// 
// Decompiled by Procyon v0.5.36
// 

package org.bukkit.attribute;

public enum Attribute
{
    GENERIC_MAX_HEALTH("GENERIC_MAX_HEALTH", 0), 
    GENERIC_FOLLOW_RANGE("GENERIC_FOLLOW_RANGE", 1), 
    GENERIC_KNOCKBACK_RESISTANCE("GENERIC_KNOCKBACK_RESISTANCE", 2), 
    GENERIC_MOVEMENT_SPEED("GENERIC_MOVEMENT_SPEED", 3), 
    GENERIC_ATTACK_DAMAGE("GENERIC_ATTACK_DAMAGE", 4), 
    GENERIC_ATTACK_SPEED("GENERIC_ATTACK_SPEED", 5), 
    GENERIC_ARMOR("GENERIC_ARMOR", 6), 
    GENERIC_LUCK("GENERIC_LUCK", 7), 
    HORSE_JUMP_STRENGTH("HORSE_JUMP_STRENGTH", 8), 
    ZOMBIE_SPAWN_REINFORCEMENTS("ZOMBIE_SPAWN_REINFORCEMENTS", 9);
    
    private Attribute(final String name, final int ordinal) {
    }
}
